# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT plants.wsgi

beta_settings:
    cloud_sql_instances: plantdatabase-51026:us-central1:mysql-plant-database

runtime_config:
  python_version: 3
# [END runtime]
